## Documentation: http://docs.travis-ci.org/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - nightly

notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly
  - os: osx

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
  - julia --project --color=yes -e "import Pkg; Pkg.instantiate(); Pkg.build();"
  - julia --check-bounds=yes --depwarn=no --color=yes --project -e "import Pkg; Pkg.test(coverage=true);"
